name = "TEDS Plus"
author = "DovydasTEDS"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46ed4e77daf21d1e601293df3dfd47265bd7340ef36c6e7d6d57fe6a933f67f1"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
